config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  root 'events#index'
  get '/carou', to:'events#carou'
  #utilisateurs
  get '/signup', to:'users#new'
  post '/signup', to:'users#create'
  #sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  #evenements
  resources :events do
    post 'attend', on: :member
    post 'unattend', on: :member
    post 'invite', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    has_and_belongs_to_many :user_attendees, :class_name => 'User', :join_table => :events_users
    belongs_to :creator, :class_name => 'User'
    validates :name,  presence: true, uniqueness: true
    validates :description,  presence: true
    validates :date,  presence: true
    validates :place,  presence: true

end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :authored_events, :foreign_key => :creator_id, :class_name => 'Event'
    has_and_belongs_to_many :attended_events, :class_name => 'Event', :join_table => :events_users
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }  
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 8 }, on: :create
  	has_secure_password

    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

def login_required
    if current_user.blank?
        redirect_to('/')
        flash[:danger] = "Connecte toi pour accéder à ta page !"
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    if logged_in?
      @event = Event.new
    else
      flash[:danger] = "Connecte toi pour créer événement !"
      redirect_to login_path
    end
  end

  def create
    @user = current_user
    @event = @user.authored_events.new(event_params)
    if @event.save
      flash[:success] = "L'événement a bien été créé !"
      redirect_to current_user
      @event.user_attendees << current_user
      @event.save
    else
      render 'new'
    end
  end

  def event_params
     params.require(:event).permit(:name, :description, :date, :place)
  end

  def show
    if logged_in?
      @event = Event.find(params[:id])
      @users = User.all
    else
      flash[:danger] = "Connecte toi pour accéder à l'événement !"
      redirect_to login_path
    end
  end

  def index
    @events = Event.all
  end

  def attend
    if logged_in?
      @event = Event.find(params[:id])
      @event.user_attendees << current_user
      @event.save
      flash[:success] = "Vous êtes inscrit à l'événement !"
      redirect_to events_path
    else
      redirect_to login_path
    end
  end

  def invite
    @event = Event.find(params[:id])
    @user = User.find(params[:user])
    @event.user_attendees << @user
    @event.save
    flash[:success] = "Vous avez ajouté votre ami à l'événement !"
    redirect_to @event
  end

  def unattend
    @event = Event.find(params[:id])
    @event.user_attendees.delete(current_user)
    @event.save
    flash[:success] = "Vous êtes désinscrit !"
    redirect_to current_user
  end

  def destroy
    @user = current_user
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = "Évenement supprimé !"
    redirect_to @current_user
  end

  def edit
    @user =  current_user
    @event = Event.find(params[:id])
    if logged_in? && current_user == @user
      edit_event_path
    else
      redirect_to login_path
    end
  end

  def update
      @user = current_user
      @event = Event.find(params[:id])
      if logged_in? && @current_user == @user
        if @event.update_attributes(event_params)
           flash[:success] = "Événement edité !"
           redirect_to event_path
       else
          render 'edit'
       end
     else
      redirect_to login_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/name combination'
      render 'new'
    end
  end
    def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required, except:[:new,:create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Bienvenue !"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if logged_in? && current_user == @user
      user_path
    else
      redirect_to login_path
    end
  end

  def update
      @user = User.find(params[:id])
      if logged_in? && @current_user == @user
      if @user.update_attributes(user_params)
        flash[:success] = "Profil edité !"
        redirect_to user_path
       else
       render 'edit'
     end
     else
      redirect_to login_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    log_out
    @user.destroy
    flash[:success] = "Ton compte a été supprimé !"
    redirect_to root_path
  end

  private

  def user_params
      params.require(:user).permit(:id, :name, :email, :password_digest, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Le meilleur site d'événements"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/carou.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carousel jQuery</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag "custom" %>
<%= stylesheet_link_tag "carou" %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

</head>
<body>
  <div class="wrapper">
    <div class="tab">
      <button class="tablinks" onclick="openTab(event, 'Accueil')">Présentation</button>
      <button class="tablinks" onclick="openTab(event, 'Menu')">Menu</button>
      <button class="tablinks" onclick="openTab(event, 'Contact')">Contact</button>
    </div>

    <div id="Accueil" class="tabcontent" style="display:block;">


    <div class="carousel">
      <div class="inner">
        <div class="slide active">
        </div>
        <div class="slide">
        </div>
        <div class="slide">
        </div>
      </div>
      <div class="arrow arrow-left"></div>
      <div class="arrow arrow-right"></div>
    </div>
    <h3>Yum Yum</h3>
    <p>Pas de photo de bouffe en stock, alors j'ai mis mes gosses. Il faut bien que ça serve !</p>
  </div>

  <div id="Menu" class="tabcontent">
    <h3>Menu</h3>
    <p>Tout plein de truc a Miam.</p>
  </div>

  <div id="Contact" class="tabcontent">
    <h3>Contact</h3>
    <p>Reserve en ligne!</p>
  </div>
  </div>
<%= javascript_include_tag "carou" %>
<%= javascript_include_tag "tab" %>
</body>
</html>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/edit.html.erb
<% provide(:title, 'Edition de Concert') %>
<h1>Édite l'événement</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event, url: event_path) do |f| %>
    <%= render 'shared/error_event_messages' %>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-glass"></i></span>
      <%= f.text_field :name, class: 'form-control', placeholder: "Nom" %>
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-edit"></i></span>
      <%= f.text_field :description, class: 'form-control', placeholder: "Description" %>
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
      <%= f.date_field :date, class: 'form-control', placeholder: "Date" %>
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-globe"></i></span>
      <%= f.text_field :place, class: 'form-control', placeholder: "Lieu" %>
    </div>
    <br>
    <%= f.submit "Éditer l'événement", class: "btn btn-sm btn-primary", method: :patch %>
    <% end %>
  </div>

app/views/events/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tabs en JS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag "custom" %>
</head>
<body>
<p>Pour le Carousel jQuery <a href="/carou">c'est par là</a></p>

<div class="tab">
  <button class="tablinks" onclick="openTab(event, 'Accueil')">Présentation</button>
  <button class="tablinks" onclick="openTab(event, 'Menu')">Menu</button>
  <button class="tablinks" onclick="openTab(event, 'Contact')">Contact</button>
</div>

<div id="Accueil" class="tabcontent" style="display:block;">
  <h3>Bienvenu au resto !</h3>
  <p>Slider ici, mais pas sans jquery donc un bon p :)</p>
</div>

<div id="Menu" class="tabcontent">
  <h3>Menu</h3>
  <p>Tout plein de truc a Miam.</p>
</div>

<div id="Contact" class="tabcontent">
  <h3>Contact</h3>
  <p>Reserve en ligne!</p>
</div>
<%= javascript_include_tag "tab" %>
</body>
</html>

app/views/events/new.html.erb
<% provide(:title, 'Nouveau concert') %>
<h1>Nouveau Concert</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event, url: events_path) do |f| %>
    <%= render 'shared/error_event_messages' %>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-glass"></i></span>
      <%= f.text_field :name, class: 'form-control', placeholder: "Nom" %>
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-edit"></i></span>
      <%= f.text_field :description, class: 'form-control', placeholder: "Description" %>
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
      <%= f.date_field :date, class: 'form-control', placeholder: "Date" %>
    </div>
    <br>
    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-globe"></i></span>
      <%= f.text_field :place, class: 'form-control', placeholder: "Lieu" %>
    </div>
    <br>
    <%= f.submit "Créer un nouvel événement", class: "btn btn-sm btn-primary" %>
    <% end %>
  </div>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>
<div class="container">
  <h1>Concert de <%= @event.name %> par <%= @event.creator.name.capitalize %></h1>
    <div id="results">
      <div class="result">
        <h2>Infos</h2>
<img src="https://s3-media1.fl.yelpcdn.com/bphoto/pqab1YHTEuGX7ciSkK6loQ/ls.jpg"/><hr>
      <p>Le concert de <%= @event.name %> se déroulera le <%= @event.date.strftime("%d/%m/%Y ") unless @event.date.nil? %>
        à <%= @event.place %></p>
       <p> <%= @event.description %> </p>
     </div>
      <% if logged_in? %>


        <% if @event.user_attendees.include?(current_user) %>
        <div class="result">
          <h2>Votre Statut</h2>
            <img src="https://s3-media1.fl.yelpcdn.com/bphoto/pqab1YHTEuGX7ciSkK6loQ/ls.jpg"/><hr>
          <h3><%= button_to 'Désinscription', unattend_event_path(@event), method: :post, confirm: 'Vraiment?',  class: "btn btn-sm btn-danger", style: "width:80%; margin:0px auto;" %></h3>
        </div>
        <% elsif @event.date > Time.now %>
        <div class="result">
          <h2>Votre Statut </h2>
          <img src="https://s3-media1.fl.yelpcdn.com/bphoto/pqab1YHTEuGX7ciSkK6loQ/ls.jpg"/><hr>
          <h3><%= button_to 'Rejoindre', attend_event_path(@event), method: :post, confirm: 'really?',  class: "btn btn-sm btn-primary", style: "width:80%; margin:0px auto;" %></h3>
        </div>
        <% end %>
      <% else %>
      <div class="result">
        <%= link_to "Inscris toi pour participer !", login_path, class: "btn btn-sm btn-primary", style:"width:80%; margin:0px auto;" %>
      </div>
      <% end %>
      <% if @event.creator == current_user %>
      <div class="result">
        <h2>Gérer ce concert</h2>
        <p> Comme vous êtes le créateur de l'événement, vous pouvez: </p>
        <h3><%= link_to "Editer", edit_event_path, method: :get, class:"btn btn-sm btn-primary", style:"width:80%; margin:0px auto;" %></h3>
      <h3> <%= link_to "Supprimer", event_path, method: :delete, class:"btn btn-sm btn-danger", style:"width:80%; margin:0px auto;", data: {confirm: 'Ultime bafouille?' } %></h3>
    </div>
      <% end %>

      <% if logged_in? %>
      <div class="result">
        <h3>Utilisateurs inscrits</h3>

            <% @event.user_attendees.each do |u|%>

              <a href="mailto:<%= u.email %>"><%= u.name %></a><br />


            <% end %>

      </div>
      <% end %>
      <% if logged_in? && @event.date > Time.now %>
      <div class="result">
        <h3>Inviter un ami</h3>
            <% @users.each do |u|%>
              <% if !(@event.user_attendees.include?(u)) && u != current_user %>
              <table style="width:90%; margin:0px auto;border:0px;">
                <tbody>
                  <tr>
                    <td style="width:60%;"><a href="mailto:<%= u.email %>"><%= u.name %></a></td>
                    <td><%= button_to 'Inviter', invite_event_path(@event), method: :post,  class: "btn btn-sm btn-warning", :params => {:user => u} %> </li>
                  </td>
                </tbody>
              </table>
             <% end %>
            <% end %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom" style="display:flex; justify-content:left; flex-wrap:wrap;">
</footer>

app/views/layouts/_head.html.erb
<head>

</head>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
     <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
     </script>
<![endif]-->

app/views/layouts/application.html.erb
<%= yield %>

app/views/shared/_error_event_messages.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@event.errors.count, "error") %>.
    </div>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<%= link_to root_path do %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, 'Inscription') %>
<h1>Edition ton profil !</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: user_path) do |f| %>
    <%= render 'shared/error_messages' %>

    <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
      <%= f.text_field :name, class: 'form-control', placeholder: "Nom" %>
    </div>
    <br>
    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
      <%= f.email_field :email, class: 'form-control', placeholder: "Email" %>
    </div>
    <br>
    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
      <%= f.password_field :password, class: 'form-control', placeholder: "Mot de passe" %>
    </div>
    <br>
    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
      <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Confirmation" %>
    </div>
    <br>
      <%= f.submit "Valider", class: "btn btn-sm btn-primary" %>
    <% end %>
    <br>
    <% if current_user == @user %>
      <%= form_for @user, method: :delete do |f| %>
    <div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
      <%= f.password_field :password, class: 'form-control', placeholder: "Mot de passe" %>
    </div>
    <br>
    <span align="center"><%= f.submit "Supprimer le compte", class: "btn btn-sm btn-primary", data: {confirm: 'Etes vous sur?' } %></span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Inscription') %>
<div id="container">
  <div id="gauche">
    <div class="bloc">
      <h1>Inscription</h1>
      <p>L'inscription devient plus simple.</p>
      <hr />
      <ul>
        <li><span class="big"><%= image_tag "surf.png" %></span> Un homme seul à Marseille</li>
        <li><span class="big"><%= image_tag "photo.png" %></span> Qui kiff la photo</li>
        <li><span class="big"><%= image_tag "css3.png" %></span> Et le CSS3</li>
      </ul>
    </div>
    <div id="droite">
          <%= form_for(@user, url: signup_path) do |f| %>
          <%= render 'shared/error_messages' %>
          <div class="input-group-1">
            <%= f.text_field :name, class: 'form-control', placeholder: "♟    Nom" %>
          </div>
          <div class="input-group">
            <%= f.email_field :email, class: 'form-control', placeholder: "✉    Email" %>
          </div>
          <div class="input-group">
            <%= f.password_field :password, class: 'form-control', placeholder: "☢    Mot de passe (>8)" %>
          </div>
          <div class="input-group-4">
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "☢    Confirmation" %>
          </div>
          <br>
          <%= f.submit "Crée ton compte !", class: "btn"%>
          <% end %>
          <div id="grey">
          <p>Connectez vous !</p>
          </div>
    </div>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
      <h1>Salut <%= @user.name %>, ça farte ?</h1>
</div>
<div>
    <section class="user_info">
      <% if current_user == @user %>
      <%= form_tag edit_user_path(@user), method: 'get' do %>
          <input style="width:20%; margin-left:40%" type="submit" value="Editer ton profil" class="btn btn-sm btn-primary">
      <% end %>
    <% end %>
    </section>
</div>
<br>
<br>
<div>
<h2>Tes concerts</h2>
<br>
<table class="table table-striped table-hover">
    <tr>
        <th>Groupe</th>
        <th>Description</th>
        <th>Date</th>
        <th>Lieu</th>
        <th></th>
        <th></i></th>
    </tr>
    <% current_user.authored_events.each do |e|%>
    <tr style="background-color: #fff;">
        <td> <%= e.name %> </td>
        <td> <%= e.description %> </td>
        <td> <%= e.date.strftime("%d/%m/%Y ") unless e.date.nil? %>  </td>
        <td> <%= e.place %> </td>
        <td> <%= button_to "Voir", e, method: :get, class:"btn btn-sm btn-primary", style:"width:100px;" %> </td>
        <% if e.creator == current_user %>
        <td> <%= button_to "Supprimer", e, method: :delete, class:"btn btn-sm btn-danger", style:"width:100px;", data: {confirm: 'Etes vous sûr?' } %></td>
        <% end %>
    </tr>
    <% end %>
</table>
</div>
<div class="center">
  <%= link_to "Nouveau Concert", new_event_path, class: "btn btn-sm btn-primary" %>
</div>
<br>
<br>
<div>
<h2>Concerts à venir</h2>
<table class="table table-striped table-hover">
    <tbody>
    <tr style="background-color: #fff;">
        <th>Groupe</th>
        <th>Description</th>
        <th>Date</th>
        <th>Lieu</th>
        <th></th>
        <th></th>
    </tr>
    <% current_user.attended_events.each do |e|%>
        <% if e.date > Time.now %>
        <tr style="background-color: #fff;">
            <td> <%= e.name %> </td>
            <td> <%= e.description %> </td>
            <td> <%= e.date.strftime("%d/%m/%Y ") %>  </td>
            <td> <%= e.place %> </td>
            <td> <%= button_to "Voir", e, method: :get, class:"btn btn-sm btn-primary", style:"width:100px;" %> </td>
              <td> <%= button_to "Se désinscrire", unattend_event_path(e), method: :post, class:"btn btn-sm btn-danger", style:"width:100px;", data: {confirm: 'Etes vous sûr?' } %> </td>
        </tr>
        <% end %>
    <% end %>
    </tbody>
</table>
</div>
<br>
<br>
<div>
<h1>Les concerts passés</h1>
<br>
<table class="table table-striped table-hover">
    <tbody>
    <tr>
        <th>Nom</th>
        <th>Description</th>
        <th>Date</th>
        <th>Lieu</th>
        <th><i class="em em-eye"></th>
    </tr>
    <% current_user.attended_events.each do |e|%>
      <% if e.date < Time.now %>
      <tr>
          <td> <%= e.name %> </td>
          <td> <%= e.description %> </td>
          <td> <%= e.date.strftime("%d/%m/%Y ") unless e.date.nil? %>  </td>
          <td> <%= e.place %> </td>
          <td> <%= link_to "Voir", e %> </td>
      </tr>
      <% end %>
    <% end %>
    </tbody>
</table>
</div>